### ISSUE TITLE
Pages have flexible content and default editor

### ISSUE THREAD

**Issue by daviddarke** [logsmith/logsmith#12]
<img width="1108" alt="screen shot 2018-01-19 at 22 20 58" src="https://user-images.githubusercontent.com/1636310/35174459-6f28eca0-fd67-11e7-9059-856eb19d778d.png">

**Comment by addidesign** [comment]
c63033757b8afe5554011c96a4af82dd64bb2a7c new acf field groups didn't have the content editor as hidden
