### ISSUE TITLE
Indenting on typo file is not consistent

### ISSUE THREAD

**Issue by daviddarke** [logsmith/logsmith#14]
Indenting on typo file is not consistent with other scss files

<img width="396" alt="screen shot 2018-01-20 at 16 51 18" src="https://user-images.githubusercontent.com/1636310/35185852-52d4788a-fe02-11e7-847e-eb5ef81341de.png">

**Comment by addidesign** [comment]
Beautified all SCSS files up! 00cc27da5bd14999986dbe15ebe48c58858f0ba8
