### ISSUE TITLE
CSS versions are getting pumped out

### ISSUE THREAD

**Issue by daviddarke** [logsmith/logsmith#16]
<img width="617" alt="screen shot 2018-01-20 at 17 34 51" src="https://user-images.githubusercontent.com/1636310/35186204-5fc697ac-fe08-11e7-9a74-344423ed9525.png">

**Comment by addidesign** [comment]
Added NPM del to manage number of revisions https://github.com/logsmith/logsmith/commit/1bc71d879bedfa9b1702f7a6e251c84894e02e10
