### ISSUE TITLE
Accordion JS and CSS can be simplified

### ISSUE THREAD

**Issue by WebAssembler** [logsmith/logsmith#36]
https://github.com/logsmith/logsmith/blob/8ff50568df8748066ccb6358bc69e6eae16fdf24/wp-content/themes/elm/assets/js/scripts.js#L118

This function checks if classes exist on the accordion and removes them if there and vice versa. The better way is to use `toggleClass` to set toggle it with the --open modifier and update the SCSS to have the accordion closed by default.

**Comment by daviddarke** [comment]
@WebAssembler 👍
